In [1]:
from google.cloud import bigquery
import pandas as pd

In [2]:
import os

In [3]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = r"E:\2026\Profile\shreeya-bigquery-analytics-lab-7e934b24f6e9.json"

In [4]:
client = bigquery.Client()

In [5]:
dataset_ref = client.dataset("iis_practise", project = "shreeya-bigquery-analytics-lab")

In [6]:
data_set= client.get_dataset(dataset_ref)

In [7]:
tables = list(client.list_tables(data_set))
for table in tables:
    print(table.table_id)

sales_lines_clean

In [8]:
table_ref = dataset_ref.table("sales_lines_clean")
table = client.get_table(table_ref)

In [9]:
client.list_rows(table, max_results=10).to_dataframe()

,int64_field_0,order_id,user_id,order_dow,order_hour_of_day,days_since_prior_order,product_id,product_name,department_id,department,qty
0,9059250,2886771,57384,5,9,6,31609,100% beef jalapeno cheeseburgers,1,frozen,1
1,9059326,679181,57384,2,17,1,31609,100% beef jalapeno cheeseburgers,1,frozen,1
2,1682139,445788,10844,6,6,6,31609,100% beef jalapeno cheeseburgers,1,frozen,1
3,5926473,3226347,37753,6,8,7,1713,100% plant protein beastley sliders,1,frozen,1
4,5925778,2551247,37753,6,15,7,1713,100% plant protein beastley sliders,1,frozen,1
5,29257671,2905366,185818,4,15,24,1713,100% plant protein beastley sliders,1,frozen,1
6,24933776,2715232,158307,5,16,7,1713,100% plant protein beastley sliders,1,frozen,1
7,26682308,1836421,169655,5,9,6,1713,100% plant protein beastley sliders,1,frozen,1
8,29145818,651170,185129,4,13,3,42438,100% vegetarian burgers grillers prime,1,frozen,1
9,923774,2919299,5956,2,14,3,12325,100% whole wheat pizza crust,1,frozen,1

In [10]:
query = """select COUNT(*) AS total_rows
        FROM `shreeya-bigquery-analytics-lab.iis_practise.sales_lines_clean`"""
rows_count = print(client.query(query).to_dataframe())

   total_rows
0    32434489

C:\Users\shree\.conda\envs\py312\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [13]:
query = """
SELECT column_name
FROM `shreeya-bigquery-analytics-lab.iis_practise.INFORMATION_SCHEMA.COLUMNS`
WHERE table_name = 'sales_lines_clean'

"""
cols_df = client.query(query).to_dataframe()
print(cols_df)

C:\Users\shree\.conda\envs\py312\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

               column_name
0            int64_field_0
1                 order_id
2                  user_id
3                order_dow
4        order_hour_of_day
5   days_since_prior_order
6               product_id
7             product_name
8            department_id
9               department
10                     qty

In [15]:
client.list_rows(table, max_results=5).to_dataframe()

,int64_field_0,order_id,user_id,order_dow,order_hour_of_day,days_since_prior_order,product_id,product_name,department_id,department,qty
0,9059250,2886771,57384,5,9,6,31609,100% beef jalapeno cheeseburgers,1,frozen,1
1,9059326,679181,57384,2,17,1,31609,100% beef jalapeno cheeseburgers,1,frozen,1
2,1682139,445788,10844,6,6,6,31609,100% beef jalapeno cheeseburgers,1,frozen,1
3,5926473,3226347,37753,6,8,7,1713,100% plant protein beastley sliders,1,frozen,1
4,5925778,2551247,37753,6,15,7,1713,100% plant protein beastley sliders,1,frozen,1

In [18]:
query = """ SELECT department,  order_dow, COUNT(1) AS products_sold
              FROM `shreeya-bigquery-analytics-lab.iis_practise.sales_lines_clean`
              GROUP BY department, order_dow """
count_of_items = print(client.query(query).to_dataframe())

C:\Users\shree\.conda\envs\py312\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

     department  order_dow  products_sold
0         other          3           4602
1        bakery          1         204386
2     beverages          6         341653
3     beverages          3         344815
4          pets          3          12589
..          ...        ...            ...
142   breakfast          0         127162
143  dairy eggs          4         635983
144   household          6         102601
145     missing          4           8174
146     missing          0          13220

[147 rows x 3 columns]

In [64]:
df = pd.read_csv("sales_lines_clean")

FileNotFoundError: [Errno 2] No such file or directory: 'sales_lines_clean'